#! /bin/sh

# Debian packaging for MinGW cross-compiled C-Pluff
# Copyright 2007 Johannes Lehtinen
# This script is free software; Johannes Lehtinen gives unlimited
# permission to copy, distribute and modify it.

# Builds the MinGW binary packages

set -e

# Check arguments
stop=
while getopts 'scbi' opt; do
    case "$opt" in
        s)
            stop=source
            ;;
        c)
            stop=configure
            ;;
        b)
            stop=build
            ;;
        i)
            stop=install
            ;;
        *)
            # Ignore unknown options
            ;;
    esac
done

basedir="`dirname "$0"`"
srcdir="$basedir/../.."
tmpdir="`mktemp -t -d`"

# Check for sources
test -f "$srcdir/libcpluff/cpluff.c"
test -f "$basedir/debian/cpluff-mingw.install"

# Copy sources and packaging files to temporary directory
cp -a "$srcdir" "$tmpdir/cpluff"
rm -rf "$tmpdir/cpluff/debian"
cp -a "$basedir/debian" "$tmpdir/cpluff"

# Check if only partial operation requested
case "$stop" in
    source)
        echo "Source is in $tmpdir/cpluff"
        exit 0
        ;;
    configure)
        (cd "$tmpdir/cpluff" && fakeroot ./debian/rules configure)
        echo "Configured source is in $tmpdir/cpluff"
        exit 0
        ;;
    build)
        (cd "$tmpdir/cpluff" && fakeroot ./debian/rules build)
        echo "Built source is in $tmpdir/cpluff"
        exit 0
        ;;
    install)
        (cd "$tmpdir/cpluff" && fakeroot ./debian/rules install)
        echo "Installed source is on $tmpdir/cpluff"
        exit 0
        ;;
esac

# Build the binary packages
(cd "$tmpdir/cpluff" && fakeroot ./debian/rules binary)

# Move the binary packages to local directory
rm -f "$basedir"/*.deb
mv "$tmpdir"/*.deb .

# Remove the temporary directory
rm -rf "$tmpdir"
