#! /bin/sh

set -e

tmpdir="tmp/test-loadmaximal"
mkdir -p "$tmpdir"
libtool --mode=execute $TEST_WRAPPER ../console/cpluff-console <<EOI > "$tmpdir"/console-out.txt
set-log-level error
load-plugin $srcdir/plugins/maximal
show-plugin-info maximal
EOI
sed -n -e '/^{$/,/^}$/{/^  plugin_path =/!p}' < "$tmpdir"/console-out.txt > "$tmpdir"/filtered.txt
diff -u "$srcdir"/expected/output-loadmaximal.txt "$tmpdir"/filtered.txt
